"""Subclass of Paramenters, which is generated by wxFormBuilder."""


from views import agaimparam_form


class Paramenters(agaimparam_form.Paramenters):
    """
    Form di gestione parametri di configurazione.
    """
    def __init__(self, parent):
        agaimparam_form.Paramenters.__init__(self, parent)

    def OnSalvaClick(self, event):
        # TODO: Implement OnSalvaClick
        pass

    def OnAnnullaClick(self, event):
        # TODO: Implement OnAnnullaClick
        pass


def paramenters_menu(event):
    """
    :param event:
    """
    param = Paramenters(None)
    param.Show()
