"""Subclass of Paramenters, which is generated by wxFormBuilder."""


from views import agaimparam_form


class ParamentersForm(agaimparam_form.Paramenters):
    """
    Form di gestione parametri di configurazione.
    """
    def __init__(self, parent):
        agaimparam_form.Paramenters.__init__(self, parent)

    def OnSalvaClick(self, event):
        # TODO: Implement OnSalvaClick
        pass

    def OnAnnullaClick(self, event):
        # TODO: Implement OnAnnullaClick
        pass


class Paramenters(object):

    def usr(self):
        # TODO: ricavare il nome utente
        return

    def pwd(self):
        # TODO: ricavare la password
        return


agaimparam = Paramenters()
