"""
Subclass of Paramenters, which is generated by wxFormBuilder.
"""

import wx

from .forms.agaimparam_form import Paramenters


class AgaimparamView(Paramenters):
    """ Form per edit dei parametri locali.
    """
    def __init__(self, parent):
        Paramenters.__init__(self, parent)
        self.Bind(wx.EVT_SHOW, self.OnLoadData)  # gestione evento Show

    def OnLoadData(self, event):
        """ Carica i parametri.
        """
        event.Skip()

    def OnSalvaClick(self, event):
        """ Salva i parametri.
        """
        event.Skip()

    def OnAnnullaClick(self, event):
        """ Chiudi la form senza modificare i parametri.
        """
        self.Close()
