"""
Subclass of Paramenters, which is generated by wxFormBuilder.
"""

import wx

from .forms.agaimparam_form import Paramenters


class AgaimparamView(Paramenters):
    """ Form per edit dei parametri locali.
    """
    def __init__(self, parent):
        Paramenters.__init__(self, parent)
        self.Bind(wx.EVT_SHOW, self.OnLoadData)  # gestione evento Show

    def OnLoadData(self, event):
        """ Carica i parametri.
        """
        event.Skip()

    def OnSalvaClick(self, event):
        """ Salva i parametri.
        """
        event.Skip()

    def OnAnnullaClick(self, event):
        """ Chiudi la form senza modificare i parametri.
        """
        self.Close()


class EditParamsView(AgaimparamView):
    """ Edit parametri tramite form.
    """
    def __init__(self, params_obj, parent=None):
        """
        :param params_obj: istanza della classe LocalParam
        """
        AgaimparamView.__init__(self, parent)
        self.params_obj = params_obj
        self.Show()

    def OnLoadData(self, event):
        """ Carica i parametri.
        """
        if event.Show:
            params = self.params_obj.params()
            for key, value in params.items():
                if key in self.__dict__.keys():
                    self.__dict__[key].Value = value

    def OnSalvaClick(self, event):
        """ Salva i parametri.
        """
        #TODO: i valori dei parametri devono essere validati prima di salvarli
        params = self.params_obj.params()
        for name in params.keys():
            if name in self.__dict__.keys():
                value = self.__dict__[name].Value
                params[name] = value
        self.params_obj.save()
        self.Close()

    def OnAnnullaClick(self, event):
        self.Close()
