"""
Subclass of Paramenters, which is generated by wxFormBuilder.

NOTA: il nome di un campo che identifica un parametro DEVE iniziare per 'param_'
"""

import wx

from .forms import agaimparam_form
from .models import load_param, save_param, UUID_PARAM


class agaimparamParamenters(agaimparam_form.Paramenters):
    def __init__(self, parent):
        agaimparam_form.Paramenters.__init__(self, parent)
        # Collego l'evento Show
        self.Bind(wx.EVT_SHOW, self.OnLoadData)

    def OnLoadData(self, event):
        """ Carica i parametri.
        """
        if event.Show:
            param = load_param()
            for param, value in param.items():
                self.__dict__[param].Value = value

    def OnSalvaClick(self, event):
        """ Salva i parametri.
        """
        params = {}
        for name, wx_ctrl in self.__dict__.items():
            if name.startswith('param_'):
                params[name] = wx_ctrl.Value
        save_param(params)
        self.Close()

    def OnAnnullaClick(self, event):
        self.Close()


def edit_param():
    """ Modifica dei parametri tramite form.
    """
    form = agaimparamParamenters(None)
    form.Show()


def get_uuid():
    params = load_param()
    return params[UUID_PARAM]
