import wx

from wx.lib.newevent import NewEvent

from gui.agaimp_gui import FrmSrvMsg


wxLogEvent, EVT_WX_LOG_EVENT = wx.lib.newevent.NewEvent()


class aGaiMpMessagesForm(FrmSrvMsg):
    """ Subclass of FrmSrvMsg, which is generated by wxFormBuilder.
    """

    def __init__(self, parent):
        FrmSrvMsg.__init__(self, parent)

        # bind del wx.TextCtrl con EVT_WX_LOG_EVENT
        self.txt_messages.Bind(EVT_WX_LOG_EVENT, self.OnLogEvent)

    def OnClose(self, event):
        self.Hide()

    def OnReset(self, event):
        pass

    def OnLogEvent(self, event):
        """ Add event.message to text window
        """
        if self.IsShown():
            msg = event.message.strip('\r')+'\n'
            self.txt_messages.AppendText(msg)
            #wx.CallAfter(self.txt_messages.AppendText, msg)
            event.Skip()
