"""Subclass of Main_Frame, which is generated by wxFormBuilder."""

import wx
import views.agaimparam

# Implementing Main_Frame
class ParametersForm( agaimparam.Main_Frame ):
	def __init__( self, parent ):
		agaimparam.Main_Frame.__init__( self, parent )
	
	# Handlers for Main_Frame events.
	def OnSalvaClick( self, event ):
		# TODO: Implement OnSalvaClick
		pass
	
	def OnAnnullaClick( self, event ):
		# TODO: Implement OnAnnullaClick
		pass
	
	
